### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by fbricon** [fbricon/pde.source.lookup#2]
because, you know...

**Comment by rgrunber** [comment]
I'm working on this. I have a basic test case that tests bringing up the classfile editor for a some attached jar when the provisioning ui is aware of the corresponding artifact repo containing the source bundle. It works when run under Eclipse, but am having some issues under tycho-surefire.

**Comment by rgrunber** [comment]
a testcase in https://github.com/fbricon/pde.source.lookup/commit/58d0457839f70415a790b40b7ca0d9d2530a36ea .

It creates a java project in the workspace and attaches the bundle jar as a library onto the classpath, as well as setting the source attachment to be the same jar (this is needed to ensure we activate). It then adds the local repository containing the corresponding source bundle to the provisioner. Finally, it passes the PackageFragmentRoot corresponding to the jar to DownloadSourcesActionDelegate which performs the source finding+fetching.

**Comment by fbricon** [comment]
Nice work, thanks a lot @rgrunber! 

I'll test it on OSX before closing the issue

**Comment by fbricon** [comment]
Tests pass on OSX on the 1st try, this is unheard of!

**Comment by rgrunber** [comment]
They don't actually run in the UI thread (for now), so that probably helps a bit.

I initially wanted to avoid calling DownloadSourcesActionDelegate, and just use JavaUI.openEditor (which would call back to the delegate through the extension point registry), but running that under tycho-surfire causes some NPEs in bringing up some parts of the workbench.

We could eventually split the test case into helper methods to make it easier to write them but it's a good start.

**Comment by fbricon** [comment]
Yeah not running with the UI thread probably caused JavaUI.openEditor to fail.
Anyway, that's a good starting point:
![](http://content.screencast.com/users/fbricon/folders/Jing/media/6c266471-618f-4b26-8d9b-3d2b245b7f92/00000390.png)

**Comment by fbricon** [comment]
Closing as it looks good to me. Thanks again @rgrunber !
